"""
Provenance Guard — multi-signal AI-content detection engine.

Three independent signals, each returning an "AI-likeness" probability in [0, 1]:

  1. burstiness  — coefficient of variation of sentence length. Humans write with
                   high burstiness (short + long sentences mixed); LLM prose is
                   uniform. Lower CV => higher AI probability.
  2. repetition  — composite of type-token ratio, repeated sentence starters, and
                   duplicate bigrams. LLMs lean on formulaic scaffolding.
  3. llm_judge   — Groq (llama-3.3-70b-versatile) estimates the probability the text
                   is machine-generated. RESTRICTIVE FALLBACK: on any error, missing
                   key, or unparseable JSON, it abstains at 0.0 so a broken LLM can
                   never *inflate* p_ai and falsely accuse a human.

Ensemble fusion:
    p_ai = 0.50 * llm + 0.25 * burstiness + 0.25 * repetition

Asymmetric classification (false positives are the costly error on a writing platform):
    p_ai >= 0.80         -> "Likely AI"      (high-confidence AI)
    0.40 <= p_ai < 0.80  -> "Uncertain"
    p_ai <  0.40         -> "Likely Human"   (high-confidence human)
"""

from __future__ import annotations

import json
import logging
import os
import re
import statistics

logger = logging.getLogger("provenance.detection")

# --- Ensemble weights (must sum to 1.0) ------------------------------------
WEIGHT_LLM = 0.50
WEIGHT_BURSTINESS = 0.25
WEIGHT_REPETITION = 0.25

# --- Classification thresholds on p_ai -------------------------------------
AI_THRESHOLD = 0.80
HUMAN_THRESHOLD = 0.40

GROQ_MODEL = "llama-3.3-70b-versatile"

# --- Transparency label variants (exact user-facing text) ------------------
LABELS = {
    "Likely AI": (
        "🤖 Likely AI-generated. Our analysis suggests this content was probably "
        "produced with the help of an AI tool. This is an automated estimate, not a "
        "certainty. The creator can appeal this label."
    ),
    "Uncertain": (
        "❔ Authorship uncertain. Our analysis could not confidently determine whether "
        "this content was written by a human or generated by AI. We are showing this "
        "honestly rather than guessing. Treat the work on its own merits."
    ),
    "Likely Human": (
        "✍️ Likely human-written. Our analysis found no strong signs of AI generation. "
        "This is an automated estimate, not a guarantee of authorship."
    ),
}


def _clamp(x: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, x))


def _split_sentences(text: str) -> list[str]:
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p.strip()]


def _words(text: str) -> list[str]:
    return re.findall(r"[A-Za-z']+", text.lower())


# ---------------------------------------------------------------------------
# Signal 1 — Burstiness
# ---------------------------------------------------------------------------
def calculate_burstiness(text: str) -> float:
    """Return AI probability from sentence-length variation. Lower CV -> higher AI."""
    try:
        sentences = _split_sentences(text)
        lengths = [len(_words(s)) for s in sentences if _words(s)]
        if len(lengths) < 2:
            # Not enough structure to judge — neutral abstain.
            return 0.5
        mean = statistics.mean(lengths)
        if mean == 0:
            return 0.5
        cv = statistics.pstdev(lengths) / mean
        # Human prose ~0.5-0.9 CV; uniform AI prose ~0.2-0.45. Map low CV -> high AI.
        return round(_clamp(1.0 - (cv / 0.9)), 4)
    except Exception:
        logger.exception("burstiness signal failed; abstaining at 0.5")
        return 0.5


# ---------------------------------------------------------------------------
# Signal 2 — Repetition
# ---------------------------------------------------------------------------
def calculate_repetition(text: str) -> float:
    """Composite repetition score: TTR + repeated openers + duplicate bigrams."""
    try:
        words = _words(text)
        sentences = _split_sentences(text)
        if len(words) < 20:
            return 0.5  # too short to measure reliably

        # (a) Type-token ratio — low diversity reads as formulaic.
        ttr = len(set(words)) / len(words)
        diversity_pen = _clamp((0.55 - ttr) / 0.40)

        # (b) Repeated sentence openers (first two words).
        openers = [" ".join(_words(s)[:2]) for s in sentences if _words(s)]
        opener_repeat = 0.0
        if openers:
            most_common = max(openers.count(o) for o in set(openers))
            opener_repeat = (most_common - 1) / len(openers)

        # (c) Duplicate bigrams.
        bigrams = list(zip(words, words[1:]))
        bigram_repeat = 0.0
        if bigrams:
            bigram_repeat = 1.0 - (len(set(bigrams)) / len(bigrams))

        score = 0.45 * diversity_pen + 0.35 * opener_repeat + 0.20 * bigram_repeat
        return round(_clamp(score), 4)
    except Exception:
        logger.exception("repetition signal failed; abstaining at 0.5")
        return 0.5


# ---------------------------------------------------------------------------
# Signal 3 — LLM judge (Groq). Restrictive fallback to 0.0.
# ---------------------------------------------------------------------------
def get_llm_judge_score(text: str) -> float:
    """
    Ask Groq for the probability the text is AI-generated.

    RESTRICTIVE FALLBACK: on a missing API key, network/API error, or JSON that
    cannot be parsed, we log loudly and return 0.0 (abstain). Defaulting low — not
    to 0.5 — guarantees a broken LLM signal can never raise p_ai and falsely flag a
    human. It can only ever pull the ensemble *toward* "human".
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.warning("GROQ_API_KEY not set — LLM judge abstaining at 0.0")
        return 0.0

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        prompt = (
            "You are an AI-text detector. Estimate the probability that the following "
            "text was generated by a large language model rather than written by a "
            "human. Consider phrasing, idiosyncrasy, factual texture, and stylistic "
            "uniformity. Respond with ONLY a JSON object of the form "
            '{"ai_probability": <float between 0 and 1>, "reason": "<one short sentence>"}.\n\n'
            f'TEXT:\n"""\n{text[:6000]}\n"""'
        )
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            max_tokens=200,
            response_format={"type": "json_object"},
        )
        content = resp.choices[0].message.content
    except Exception:
        logger.exception("Groq API call failed — LLM judge abstaining at 0.0")
        return 0.0

    # Parse the structured JSON separately so parse failures are handled loudly.
    try:
        data = json.loads(content)
        score = float(data["ai_probability"])
        return round(_clamp(score), 4)
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        logger.error(
            "LLM judge returned unparseable JSON (%r) — abstaining at 0.0", content
        )
        return 0.0


# ---------------------------------------------------------------------------
# Ensemble + classification
# ---------------------------------------------------------------------------
# Machine-readable attribution codes (snake_case) paired with each classification.
ATTRIBUTION = {
    "Likely AI": "likely_ai",
    "Uncertain": "uncertain",
    "Likely Human": "likely_human",
}


def _classify(p_ai: float) -> str:
    if p_ai >= AI_THRESHOLD:
        return "Likely AI"
    if p_ai < HUMAN_THRESHOLD:
        return "Likely Human"
    return "Uncertain"


def evaluate_content(text: str) -> dict:
    """
    Run all three signals, fuse them into p_ai, map to a classification, and
    select the exact transparency label. Always returns a fully-populated dict,
    even when individual signals abstain.
    """
    burstiness_score = calculate_burstiness(text)
    repetition_score = calculate_repetition(text)
    llm_score = get_llm_judge_score(text)

    p_ai = _clamp(
        WEIGHT_LLM * llm_score
        + WEIGHT_BURSTINESS * burstiness_score
        + WEIGHT_REPETITION * repetition_score
    )
    p_ai = round(p_ai, 4)

    classification = _classify(p_ai)

    # Confidence = certainty in whichever direction the score leans. High for a
    # clear human or clear AI verdict; low (~0.5) for genuinely borderline text.
    confidence = round(max(p_ai, 1.0 - p_ai), 4)

    return {
        "text": text,
        "burstiness_score": burstiness_score,
        "repetition_score": repetition_score,
        "llm_score": llm_score,
        "final_p_ai": p_ai,
        "content_type": "text",
        "classification": classification,
        "attribution": ATTRIBUTION[classification],
        "confidence": confidence,
        "transparency_label": LABELS[classification],
        "signals_detail": {
            "burstiness": burstiness_score,
            "repetition": repetition_score,
            "llm": llm_score,
        },
        "weights": {
            "llm": WEIGHT_LLM,
            "burstiness": WEIGHT_BURSTINESS,
            "repetition": WEIGHT_REPETITION,
        },
    }


# ---------------------------------------------------------------------------
# Multi-modal support (stretch feature) — image metadata pipeline
# ---------------------------------------------------------------------------
# Known AI image generators; a match in the software/tool metadata is a strong tell.
_AI_IMAGE_TOOLS = (
    "midjourney", "stable diffusion", "stablediffusion", "dall-e", "dall·e", "dalle",
    "adobe firefly", "firefly", "imagen", "flux", "ideogram", "leonardo", "nightcafe",
    "gan", "generative", "ai",
)

IMAGE_WEIGHTS = {
    "generation_software": 0.40,
    "generation_prompt": 0.30,
    "missing_camera_exif": 0.15,
    "c2pa_provenance": 0.15,
}


def _str(v) -> str:
    return str(v).lower() if v is not None else ""


def evaluate_image_metadata(metadata: dict) -> dict:
    """
    Independent signal set for the IMAGE modality, run over structured metadata rather
    than prose. Reuses the same thresholds, attribution codes, and transparency labels
    as the text pipeline so confidence semantics and label UX are identical.

    Recognized metadata keys (all optional): software / tool / creator_tool, prompt /
    generation_prompt, camera_make / camera_model / exif, c2pa (dict with
    'ai_generated' or 'camera_captured' booleans).
    """
    software = " ".join(
        _str(metadata.get(k)) for k in ("software", "tool", "creator_tool")
    )
    software_hit = any(t in software for t in _AI_IMAGE_TOOLS) if software.strip() else False
    sig_software = 1.0 if software_hit else 0.0

    has_prompt = bool(metadata.get("prompt") or metadata.get("generation_prompt"))
    sig_prompt = 1.0 if has_prompt else 0.0

    has_camera = bool(
        metadata.get("camera_make") or metadata.get("camera_model") or metadata.get("exif")
    )
    sig_missing_exif = 0.7 if not has_camera else 0.0

    c2pa = metadata.get("c2pa") or {}
    if c2pa.get("ai_generated"):
        sig_c2pa = 1.0
    elif c2pa.get("camera_captured"):
        sig_c2pa = 0.0
    else:
        sig_c2pa = 0.5  # no verifiable provenance manifest either way

    p_ai = _clamp(
        IMAGE_WEIGHTS["generation_software"] * sig_software
        + IMAGE_WEIGHTS["generation_prompt"] * sig_prompt
        + IMAGE_WEIGHTS["missing_camera_exif"] * sig_missing_exif
        + IMAGE_WEIGHTS["c2pa_provenance"] * sig_c2pa
    )
    p_ai = round(p_ai, 4)

    classification = _classify(p_ai)
    confidence = round(max(p_ai, 1.0 - p_ai), 4)

    summary = (
        f"[image] software={software.strip() or 'n/a'}, prompt={has_prompt}, "
        f"camera_exif={has_camera}, c2pa={c2pa or 'n/a'}"
    )

    return {
        "text": summary,  # snapshot for the audit-log snippet
        "final_p_ai": p_ai,
        "content_type": "image_metadata",
        "classification": classification,
        "attribution": ATTRIBUTION[classification],
        "confidence": confidence,
        "transparency_label": LABELS[classification],
        "signals_detail": {
            "generation_software": sig_software,
            "generation_prompt": sig_prompt,
            "missing_camera_exif": sig_missing_exif,
            "c2pa_provenance": sig_c2pa,
        },
        "weights": IMAGE_WEIGHTS,
    }
